# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://theportus.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "A Jekyll Template"
description: A Jekyll Template, based on Tailpages

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

nav-menu:
- text: About
  permalink: about
- text: Tags
  permalink: tags

# use false to turn off any social media links, otherwise include link to profile
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# google-analytics: // if you want to use Google analytics, include your ID here

include:
  - _pages

paginate: 5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
